[repository]
name = "hyprstack"
authors = ["ver-1000000"]

[hyprstack]
description = "Workspace-local stable window stack semantics for Hyprland"
authors = ["ver-1000000"]
output = "build/hyprstack.so"
build = ["make all"]
